# All website project options: https://quarto.org/docs/reference/projects/websites.html
project:
  type: website
  output-dir: docs
  resources:
    - CNAME
    # - .nojekyll
  preview: 
    browser: true
execute:
  freeze: auto
anchor-sections: false
  
profile: 
  default: active
  group: [active, inactive, semiactive]

website:
  title: "Dr Tormey Reimer"
  description: "Welcome to my personal website."
  favicon: resources/icons/water-solid-light.svg
  site-url: https://www.drtreimer.com
  repo-url: https://github.com/stormeyseas/stormeyseas.github.io
  reader-mode: false
  bread-crumbs: false
  # Allows some pages to have a sidebar
  sidebar: 
    - id: sidebar1 
      # title: " "
      style: "docked"
      border: false
      contents: "auto"
      background: light
      foreground: light

# Navbar options (see https://quarto.org/docs/reference/projects/websites.html#navbar)
  navbar: 
    title: false
    logo: /resources/icons/water-solid-light.svg
    pinned: false
    collapse: true
    # List of items for the each section of the navbar (left, right, center)
    right: 
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Projects
        href: projects.qmd
      - text: Publications
        href: publications.qmd
      - text: Blog
        href: blog.qmd
      - text: Contact
        href: contact.qmd
    toggle-position: right # The position of the collapsed navbar toggle when in responsive mode
  page-navigation: false
  back-to-top-navigation: false
  page-footer:
    left: |
      [</i><img src="/resources/icons/envelope-solid-light.svg" class="img-fluid" style="height: 1.5em; valign: middle;">](mailto:tormey.reimer@utas.edu.au) [tormey.reimer@utas.edu.au](mailto:tormey.reimer@utas.edu.au)<br>
      [![](/resources/icons/researchgate-light.svg){fig-alt="ResearchGate" fig-align="center" height="1.5em" fig-valign="top" margin-left="10px" margin-right="10px"}](https://www.researchgate.net/profile/Tormey-Reimer)
      [![](/resources/icons/orcid-light.svg){fig-alt="OrcID" fig-align="center" height="1.5em" fig-valign="top" margin-left="10px" margin-right="10px"}](https://orcid.org/0000-0002-5983-2798)
      [![](/resources/icons/linkedin-light.svg){fig-alt="LinkedIN" fig-align="center" height="1.5em" fig-valign="top" margin-left="10px" margin-right="10px"}](https://au.linkedin.com/in/tormey-reimer)
      [![](/resources/icons/google-scholar-light.svg){fig-alt="GoogleScholar" fig-align="center" height="1.5em" fig-valign="top" margin-left="10px" margin-right="10px"}](https://scholar.google.com.au/citations?user=H45vLccAAAAJ&hl=en)
      [![](/resources/icons/github-light.svg){fig-alt="Github" fig-align="center" height="1.5em" fig-valign="top" margin-left="10px" margin-right="10px"}](https://github.com)
      <br><br>
      Website created by [me](/projects.qmd#sec-this-website)!
    right: |
      <i>I live and work on the land of the Wurundjeri people.<br>
      IMAS is built on the land of the Muwinina people, which the Palawa people continue to care for today.<br>
      Sovereignty was never ceded  </i><img src="/resources/images/Australian_Aboriginal_Flag.png" class="img-fluid" style="height: 1em;">
    background: dark
    foreground: light

format:
  html:
    theme:
      light: resources/styling/my-theme.scss
      dark: resources/styling/my-theme.scss
    css: resources/styling/styles.css
    page-layout: full
    grid:
      sidebar-width: 225px
      body-width: 1500px
      margin-width: 75px
      gutter-width: 1.5em
    toc: false
    fig-responsive: true
