# All website project options: https://quarto.org/docs/reference/projects/websites.html
project:
  type: website
  output-dir: site-files
  preview: 
    browser: true

website:
  title: "Tormey E Reimer"
  description: "Welcome to my personal website."
  favicon: pictures/pgntree-shiny-gold-star.png # Choose a new favicon
  site-url: https://www.drtreimer.com
  repo-url: https://github.com/stormeyseas/stormeyseas.github.io
  reader-mode: false # Displays a ‘reader-mode’ tool which allows users to hide the sidebar and table of contents when viewing a page.
  # Create a bunch of different sidebars and put a "dummy" one on the homepage.
  sidebar: 
    - id: dummysidebar 
      title: " "
      style: "docked"
      background: light
      foreground: light
      border: false
    - id: normalsidebar
      title: "Look around" # Uses the project title if none is specified
      contents: "auto"
      style: "docked"
      background: light
      foreground: dark
      border: true # defaults to true for ‘docked’, false for 'floating'
      alignment: 'left'
  navbar: # Navbar options (see https://quarto.org/docs/reference/projects/websites.html#navbar)
    title: " " # Uses the project title if none is specified.
    pinned: true
    collapse: true
    # List of items for the each section of the navbar (left, right, center)
    left: 
      - href: pages/index.qmd
        text: "Home"
      - href: pages/about.qmd
        text: "About"
      - href: pages/blog.qmd
        text: "Blog"
    toggle-position: left # The position of the collapsed navbar toggle when in responsive mode
  page-navigation: false # Provide next and previous article links in footer
  back-to-top-navigation: false
  # Page footer. Text content or page footer definition. I want some links behind cute icons here
  page-footer: 
    left: |
      <br>
      Contact: [tormey.reimer@utas.edu.au](mailto:tormey.reimer@utas.edu.au)
    right: |
      <br>
      <i>I acknowledge the traditional owners of the land on which I live and work. Sovereignty was never ceded </i>
      ![](/resources/pictures/Australian_Aboriginal_flag.png){height=0.8em fig-valign=top}
      <br>
    border: false
    background: dark
    foreground: light

format:
  html:
    theme: lux
    css: styles.css
    # This is where custom theme elements will go
    page-layout: full
    toc: true
    fig-responsive: true
